-- 006_create_finanzas_module.sql

-- 1. Create saldos table
CREATE TABLE IF NOT EXISTS saldos (
    id_saldo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caja_chica NUMERIC(18,2) NOT NULL DEFAULT 0,
    cuenta_banco NUMERIC(18,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Initialize saldos with a single row if empty
INSERT INTO saldos (caja_chica, cuenta_banco)
SELECT 0, 0
WHERE NOT EXISTS (SELECT 1 FROM saldos);

-- 2. Create gasto table
CREATE TABLE IF NOT EXISTS gasto (
    id_gasto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    concepto VARCHAR(255) NOT NULL,
    monto NUMERIC(18,2) NOT NULL CHECK (monto >= 0),
    categoria VARCHAR(100) NOT NULL,
    metodo_pago VARCHAR(50) NOT NULL,
    id_user INT,
    id_compra INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_gasto_compra FOREIGN KEY (id_compra) REFERENCES compra(id_compra) ON DELETE SET NULL,
    CONSTRAINT fk_gasto_usuario FOREIGN KEY (id_user) REFERENCES auth_user(id_user) ON DELETE SET NULL
);

-- 3. Trigger for income tracking (from pago)
CREATE OR REPLACE FUNCTION fn_sync_ingreso_saldos()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.forma_pago ILIKE '%Efectivo%' THEN
        UPDATE saldos SET caja_chica = caja_chica + NEW.monto, updated_at = NOW();
    ELSE
        UPDATE saldos SET cuenta_banco = cuenta_banco + NEW.monto, updated_at = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_ingreso_saldos ON pago;
CREATE TRIGGER trg_sync_ingreso_saldos
AFTER INSERT ON pago
FOR EACH ROW
EXECUTE FUNCTION fn_sync_ingreso_saldos();

-- 4. Trigger for gasto tracking and Landed Cost (Fletes)
CREATE OR REPLACE FUNCTION fn_gasto_saldos_y_landed_cost()
RETURNS TRIGGER AS $$
DECLARE
    v_total_compra NUMERIC(18,2);
BEGIN
    -- 1. Deduct from saldos
    IF NEW.metodo_pago ILIKE '%Efectivo%' THEN
        UPDATE saldos SET caja_chica = caja_chica - NEW.monto, updated_at = NOW();
    ELSE
        UPDATE saldos SET cuenta_banco = cuenta_banco - NEW.monto, updated_at = NOW();
    END IF;

    -- 2. Prorate Landed Cost
    IF NEW.categoria = 'Flete/Paquetería' AND NEW.id_compra IS NOT NULL THEN
        -- Get total of the purchase
        SELECT SUM(importe) INTO v_total_compra
        FROM detalle_compra
        WHERE id_compra = NEW.id_compra;

        IF v_total_compra IS NOT NULL AND v_total_compra > 0 THEN
            -- Proportionally update costo_unitario and importe based on value distribution
            UPDATE detalle_compra
            SET costo_unitario = costo_unitario + ((NEW.monto * importe / v_total_compra) / cantidad),
                importe = importe + (NEW.monto * importe / v_total_compra)
            WHERE id_compra = NEW.id_compra AND cantidad > 0;
            
            -- Update total in compra table
            UPDATE compra 
            SET total = total + NEW.monto
            WHERE id_compra = NEW.id_compra;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_gasto_saldos_y_landed_cost ON gasto;
CREATE TRIGGER trg_gasto_saldos_y_landed_cost
AFTER INSERT ON gasto
FOR EACH ROW
EXECUTE FUNCTION fn_gasto_saldos_y_landed_cost();
