-- 015_create_producto_cotizacion_prov.sql

CREATE TABLE IF NOT EXISTS producto_cotizacion_prov (
    id_cotizacion_prov INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INT NOT NULL,
    id_proveedor INT NOT NULL,
    marca_ofrecida VARCHAR(100),
    precio_cotizado NUMERIC(10,2) NOT NULL CHECK (precio_cotizado >= 0),
    dias_entrega INT NOT NULL DEFAULT 0 CHECK (dias_entrega >= 0),
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT fk_prod_cotiz_producto FOREIGN KEY (id_producto) REFERENCES producto("IdProducto") ON DELETE CASCADE,
    CONSTRAINT fk_prod_cotiz_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedor("IdProveedor") ON DELETE CASCADE
);

-- Index for faster history retrieval by product
CREATE INDEX IF NOT EXISTS idx_prod_cotiz_producto ON producto_cotizacion_prov(id_producto);
